#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

if env | grep -q "FFS_SCHEDULED_BATCH_JOB_"
then
    echo "false"
else
    echo "true"
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
